### ISSUE TITLE
ERROR: "Invalid file descriptor. File possibly closed by a different thread" error on adding url of unfinished file

### ISSUE THREAD

**Issue by NIC8146** [ProjectMile/Mile.Aria2#2]
aria2::run(session, aria2::RUN_ONCE) is running on different thread , on adding uri to download unfinished file which is removed previously show error "Invalid file descriptor. File possibly closed by a different thread" but no file is closed on debug every thing look fine
![Error](https://github.com/ProjectMile/Mile.Aria2/assets/52288863/20eb57f7-b2ea-4043-ba21-b109c6ce96db)

**Comment by MouriNaruto** [comment]
I have merged the related PR. Thank you very much.

Kenji Mouri
